#!/bin/sh


mkdir -p /dev /proc /sys /mnt

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs /dev /dev

mount /dev/sda1 /mnt

cat /etc/motd
echo "inserting the kernel module:"
insmod /etc/modules/mod.ko

exec /bin/sh
exec switch_root /mnt /bin/systemd # /bin/sh
