#!/bin/sh

mkdir -p /proc /sys /dev
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devfs none /dev

hostname -F /etc/hostname

cat /etc/motd
sleep 1

# /main 10000 h
# /main 10000 t

exec /bin/sh
